[tool.poetry]
name = "digdigdrill-solver"
version = "0.1.0"
description = ""
authors = ["misc4747 <misc4747@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
